#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corpore_Imoveis
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CORPORE_IMO_SOAP")]
	public partial class CORPORE_IMO_SOAPDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertXDESPESA(XDESPESA instance);
    partial void UpdateXDESPESA(XDESPESA instance);
    partial void DeleteXDESPESA(XDESPESA instance);
    #endregion
		
		public CORPORE_IMO_SOAPDataContext() : 
				base(global::Corpore_Imoveis.Properties.Settings.Default.CORPORE_IMO_SOAPConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CORPORE_IMO_SOAPDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CORPORE_IMO_SOAPDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CORPORE_IMO_SOAPDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CORPORE_IMO_SOAPDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<XDESPESA> XDESPESAs
		{
			get
			{
				return this.GetTable<XDESPESA>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.XDESPESA")]
	public partial class XDESPESA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _CODCOLIGADA;
		
		private int _CODDESPESA;
		
		private string _DESCDESPESA;
		
		private short _ORIGEM;
		
		private int _CODPARAMMVTO;
		
		private int _CODTIPODESPESA;
		
		private short _NUMPARCELA;
		
		private string _PERMITEREEMBOLSO;
		
		private System.Nullable<int> _CODREGRAREEMBOLSO;
		
		private System.Nullable<short> _NUMPARCELAREEMBOLSO;
		
		private short _CODCOLCFO;
		
		private string _CODCFO;
		
		private string _RECCREATEDBY;
		
		private System.Nullable<System.DateTime> _RECCREATEDON;
		
		private string _RECMODIFIEDBY;
		
		private System.Nullable<System.DateTime> _RECMODIFIEDON;
		
		private System.Nullable<int> _CODIMOVEL;
		
		private System.Nullable<int> _IDINSCRICAOMUNICIPAL;
		
		private System.Nullable<System.DateTime> _COMPETENCIA;
		
		private System.Nullable<short> _STATUS;
		
		private string _NUMERODOCUMENTO;
		
		private System.Nullable<decimal> _VALORAVISTA;
		
		private System.Nullable<decimal> _VALORAPRAZO;
		
		private System.Nullable<System.DateTime> _PRIMEIROVENCIMENTO;
		
		private System.Nullable<short> _INTERVALODIAS;
		
		private System.Nullable<short> _TIPOVALORDESPESA;
		
		private System.Nullable<short> _TIPOVALORREEMBOLSO;
		
		private System.Nullable<int> _IDPARAMFIN;
		
		private System.Nullable<int> _COD_PESS_EMPR;
		
		private string _NUM_UNID;
		
		private string _NUM_SUB_UNID;
		
		private System.Nullable<int> _INTERVALODIASREEMBOLSO;
		
		private System.Nullable<int> _ANOEXERCICIO;
		
		private System.Nullable<int> _CODSEGURO;
		
		private System.Nullable<System.DateTime> _PRIMEIROVCTOREEMBOLSO;
		
		private int _PERIODICIDADE;
		
		private int _PERIODICIDADEREEMBOLSO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODCOLIGADAChanging(short value);
    partial void OnCODCOLIGADAChanged();
    partial void OnCODDESPESAChanging(int value);
    partial void OnCODDESPESAChanged();
    partial void OnDESCDESPESAChanging(string value);
    partial void OnDESCDESPESAChanged();
    partial void OnORIGEMChanging(short value);
    partial void OnORIGEMChanged();
    partial void OnCODPARAMMVTOChanging(int value);
    partial void OnCODPARAMMVTOChanged();
    partial void OnCODTIPODESPESAChanging(int value);
    partial void OnCODTIPODESPESAChanged();
    partial void OnNUMPARCELAChanging(short value);
    partial void OnNUMPARCELAChanged();
    partial void OnPERMITEREEMBOLSOChanging(string value);
    partial void OnPERMITEREEMBOLSOChanged();
    partial void OnCODREGRAREEMBOLSOChanging(System.Nullable<int> value);
    partial void OnCODREGRAREEMBOLSOChanged();
    partial void OnNUMPARCELAREEMBOLSOChanging(System.Nullable<short> value);
    partial void OnNUMPARCELAREEMBOLSOChanged();
    partial void OnCODCOLCFOChanging(short value);
    partial void OnCODCOLCFOChanged();
    partial void OnCODCFOChanging(string value);
    partial void OnCODCFOChanged();
    partial void OnRECCREATEDBYChanging(string value);
    partial void OnRECCREATEDBYChanged();
    partial void OnRECCREATEDONChanging(System.Nullable<System.DateTime> value);
    partial void OnRECCREATEDONChanged();
    partial void OnRECMODIFIEDBYChanging(string value);
    partial void OnRECMODIFIEDBYChanged();
    partial void OnRECMODIFIEDONChanging(System.Nullable<System.DateTime> value);
    partial void OnRECMODIFIEDONChanged();
    partial void OnCODIMOVELChanging(System.Nullable<int> value);
    partial void OnCODIMOVELChanged();
    partial void OnIDINSCRICAOMUNICIPALChanging(System.Nullable<int> value);
    partial void OnIDINSCRICAOMUNICIPALChanged();
    partial void OnCOMPETENCIAChanging(System.Nullable<System.DateTime> value);
    partial void OnCOMPETENCIAChanged();
    partial void OnSTATUSChanging(System.Nullable<short> value);
    partial void OnSTATUSChanged();
    partial void OnNUMERODOCUMENTOChanging(string value);
    partial void OnNUMERODOCUMENTOChanged();
    partial void OnVALORAVISTAChanging(System.Nullable<decimal> value);
    partial void OnVALORAVISTAChanged();
    partial void OnVALORAPRAZOChanging(System.Nullable<decimal> value);
    partial void OnVALORAPRAZOChanged();
    partial void OnPRIMEIROVENCIMENTOChanging(System.Nullable<System.DateTime> value);
    partial void OnPRIMEIROVENCIMENTOChanged();
    partial void OnINTERVALODIASChanging(System.Nullable<short> value);
    partial void OnINTERVALODIASChanged();
    partial void OnTIPOVALORDESPESAChanging(System.Nullable<short> value);
    partial void OnTIPOVALORDESPESAChanged();
    partial void OnTIPOVALORREEMBOLSOChanging(System.Nullable<short> value);
    partial void OnTIPOVALORREEMBOLSOChanged();
    partial void OnIDPARAMFINChanging(System.Nullable<int> value);
    partial void OnIDPARAMFINChanged();
    partial void OnCOD_PESS_EMPRChanging(System.Nullable<int> value);
    partial void OnCOD_PESS_EMPRChanged();
    partial void OnNUM_UNIDChanging(string value);
    partial void OnNUM_UNIDChanged();
    partial void OnNUM_SUB_UNIDChanging(string value);
    partial void OnNUM_SUB_UNIDChanged();
    partial void OnINTERVALODIASREEMBOLSOChanging(System.Nullable<int> value);
    partial void OnINTERVALODIASREEMBOLSOChanged();
    partial void OnANOEXERCICIOChanging(System.Nullable<int> value);
    partial void OnANOEXERCICIOChanged();
    partial void OnCODSEGUROChanging(System.Nullable<int> value);
    partial void OnCODSEGUROChanged();
    partial void OnPRIMEIROVCTOREEMBOLSOChanging(System.Nullable<System.DateTime> value);
    partial void OnPRIMEIROVCTOREEMBOLSOChanged();
    partial void OnPERIODICIDADEChanging(int value);
    partial void OnPERIODICIDADEChanged();
    partial void OnPERIODICIDADEREEMBOLSOChanging(int value);
    partial void OnPERIODICIDADEREEMBOLSOChanged();
    #endregion
		
		public XDESPESA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODCOLIGADA", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short CODCOLIGADA
		{
			get
			{
				return this._CODCOLIGADA;
			}
			set
			{
				if ((this._CODCOLIGADA != value))
				{
					this.OnCODCOLIGADAChanging(value);
					this.SendPropertyChanging();
					this._CODCOLIGADA = value;
					this.SendPropertyChanged("CODCOLIGADA");
					this.OnCODCOLIGADAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODDESPESA", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CODDESPESA
		{
			get
			{
				return this._CODDESPESA;
			}
			set
			{
				if ((this._CODDESPESA != value))
				{
					this.OnCODDESPESAChanging(value);
					this.SendPropertyChanging();
					this._CODDESPESA = value;
					this.SendPropertyChanged("CODDESPESA");
					this.OnCODDESPESAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCDESPESA", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DESCDESPESA
		{
			get
			{
				return this._DESCDESPESA;
			}
			set
			{
				if ((this._DESCDESPESA != value))
				{
					this.OnDESCDESPESAChanging(value);
					this.SendPropertyChanging();
					this._DESCDESPESA = value;
					this.SendPropertyChanged("DESCDESPESA");
					this.OnDESCDESPESAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORIGEM", DbType="SmallInt NOT NULL")]
		public short ORIGEM
		{
			get
			{
				return this._ORIGEM;
			}
			set
			{
				if ((this._ORIGEM != value))
				{
					this.OnORIGEMChanging(value);
					this.SendPropertyChanging();
					this._ORIGEM = value;
					this.SendPropertyChanged("ORIGEM");
					this.OnORIGEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODPARAMMVTO", DbType="Int NOT NULL")]
		public int CODPARAMMVTO
		{
			get
			{
				return this._CODPARAMMVTO;
			}
			set
			{
				if ((this._CODPARAMMVTO != value))
				{
					this.OnCODPARAMMVTOChanging(value);
					this.SendPropertyChanging();
					this._CODPARAMMVTO = value;
					this.SendPropertyChanged("CODPARAMMVTO");
					this.OnCODPARAMMVTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODTIPODESPESA", DbType="Int NOT NULL")]
		public int CODTIPODESPESA
		{
			get
			{
				return this._CODTIPODESPESA;
			}
			set
			{
				if ((this._CODTIPODESPESA != value))
				{
					this.OnCODTIPODESPESAChanging(value);
					this.SendPropertyChanging();
					this._CODTIPODESPESA = value;
					this.SendPropertyChanged("CODTIPODESPESA");
					this.OnCODTIPODESPESAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMPARCELA", DbType="SmallInt NOT NULL")]
		public short NUMPARCELA
		{
			get
			{
				return this._NUMPARCELA;
			}
			set
			{
				if ((this._NUMPARCELA != value))
				{
					this.OnNUMPARCELAChanging(value);
					this.SendPropertyChanging();
					this._NUMPARCELA = value;
					this.SendPropertyChanged("NUMPARCELA");
					this.OnNUMPARCELAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERMITEREEMBOLSO", DbType="VarChar(1)")]
		public string PERMITEREEMBOLSO
		{
			get
			{
				return this._PERMITEREEMBOLSO;
			}
			set
			{
				if ((this._PERMITEREEMBOLSO != value))
				{
					this.OnPERMITEREEMBOLSOChanging(value);
					this.SendPropertyChanging();
					this._PERMITEREEMBOLSO = value;
					this.SendPropertyChanged("PERMITEREEMBOLSO");
					this.OnPERMITEREEMBOLSOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODREGRAREEMBOLSO", DbType="Int")]
		public System.Nullable<int> CODREGRAREEMBOLSO
		{
			get
			{
				return this._CODREGRAREEMBOLSO;
			}
			set
			{
				if ((this._CODREGRAREEMBOLSO != value))
				{
					this.OnCODREGRAREEMBOLSOChanging(value);
					this.SendPropertyChanging();
					this._CODREGRAREEMBOLSO = value;
					this.SendPropertyChanged("CODREGRAREEMBOLSO");
					this.OnCODREGRAREEMBOLSOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMPARCELAREEMBOLSO", DbType="SmallInt")]
		public System.Nullable<short> NUMPARCELAREEMBOLSO
		{
			get
			{
				return this._NUMPARCELAREEMBOLSO;
			}
			set
			{
				if ((this._NUMPARCELAREEMBOLSO != value))
				{
					this.OnNUMPARCELAREEMBOLSOChanging(value);
					this.SendPropertyChanging();
					this._NUMPARCELAREEMBOLSO = value;
					this.SendPropertyChanged("NUMPARCELAREEMBOLSO");
					this.OnNUMPARCELAREEMBOLSOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODCOLCFO", DbType="SmallInt NOT NULL")]
		public short CODCOLCFO
		{
			get
			{
				return this._CODCOLCFO;
			}
			set
			{
				if ((this._CODCOLCFO != value))
				{
					this.OnCODCOLCFOChanging(value);
					this.SendPropertyChanging();
					this._CODCOLCFO = value;
					this.SendPropertyChanged("CODCOLCFO");
					this.OnCODCOLCFOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODCFO", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string CODCFO
		{
			get
			{
				return this._CODCFO;
			}
			set
			{
				if ((this._CODCFO != value))
				{
					this.OnCODCFOChanging(value);
					this.SendPropertyChanging();
					this._CODCFO = value;
					this.SendPropertyChanged("CODCFO");
					this.OnCODCFOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECCREATEDBY", DbType="VarChar(50)")]
		public string RECCREATEDBY
		{
			get
			{
				return this._RECCREATEDBY;
			}
			set
			{
				if ((this._RECCREATEDBY != value))
				{
					this.OnRECCREATEDBYChanging(value);
					this.SendPropertyChanging();
					this._RECCREATEDBY = value;
					this.SendPropertyChanged("RECCREATEDBY");
					this.OnRECCREATEDBYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECCREATEDON", DbType="DateTime2")]
		public System.Nullable<System.DateTime> RECCREATEDON
		{
			get
			{
				return this._RECCREATEDON;
			}
			set
			{
				if ((this._RECCREATEDON != value))
				{
					this.OnRECCREATEDONChanging(value);
					this.SendPropertyChanging();
					this._RECCREATEDON = value;
					this.SendPropertyChanged("RECCREATEDON");
					this.OnRECCREATEDONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECMODIFIEDBY", DbType="VarChar(50)")]
		public string RECMODIFIEDBY
		{
			get
			{
				return this._RECMODIFIEDBY;
			}
			set
			{
				if ((this._RECMODIFIEDBY != value))
				{
					this.OnRECMODIFIEDBYChanging(value);
					this.SendPropertyChanging();
					this._RECMODIFIEDBY = value;
					this.SendPropertyChanged("RECMODIFIEDBY");
					this.OnRECMODIFIEDBYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECMODIFIEDON", DbType="DateTime2")]
		public System.Nullable<System.DateTime> RECMODIFIEDON
		{
			get
			{
				return this._RECMODIFIEDON;
			}
			set
			{
				if ((this._RECMODIFIEDON != value))
				{
					this.OnRECMODIFIEDONChanging(value);
					this.SendPropertyChanging();
					this._RECMODIFIEDON = value;
					this.SendPropertyChanged("RECMODIFIEDON");
					this.OnRECMODIFIEDONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIMOVEL", DbType="Int")]
		public System.Nullable<int> CODIMOVEL
		{
			get
			{
				return this._CODIMOVEL;
			}
			set
			{
				if ((this._CODIMOVEL != value))
				{
					this.OnCODIMOVELChanging(value);
					this.SendPropertyChanging();
					this._CODIMOVEL = value;
					this.SendPropertyChanged("CODIMOVEL");
					this.OnCODIMOVELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDINSCRICAOMUNICIPAL", DbType="Int")]
		public System.Nullable<int> IDINSCRICAOMUNICIPAL
		{
			get
			{
				return this._IDINSCRICAOMUNICIPAL;
			}
			set
			{
				if ((this._IDINSCRICAOMUNICIPAL != value))
				{
					this.OnIDINSCRICAOMUNICIPALChanging(value);
					this.SendPropertyChanging();
					this._IDINSCRICAOMUNICIPAL = value;
					this.SendPropertyChanged("IDINSCRICAOMUNICIPAL");
					this.OnIDINSCRICAOMUNICIPALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPETENCIA", DbType="DateTime2")]
		public System.Nullable<System.DateTime> COMPETENCIA
		{
			get
			{
				return this._COMPETENCIA;
			}
			set
			{
				if ((this._COMPETENCIA != value))
				{
					this.OnCOMPETENCIAChanging(value);
					this.SendPropertyChanging();
					this._COMPETENCIA = value;
					this.SendPropertyChanged("COMPETENCIA");
					this.OnCOMPETENCIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="SmallInt")]
		public System.Nullable<short> STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMERODOCUMENTO", DbType="VarChar(40)")]
		public string NUMERODOCUMENTO
		{
			get
			{
				return this._NUMERODOCUMENTO;
			}
			set
			{
				if ((this._NUMERODOCUMENTO != value))
				{
					this.OnNUMERODOCUMENTOChanging(value);
					this.SendPropertyChanging();
					this._NUMERODOCUMENTO = value;
					this.SendPropertyChanged("NUMERODOCUMENTO");
					this.OnNUMERODOCUMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALORAVISTA", DbType="Decimal(15,4)")]
		public System.Nullable<decimal> VALORAVISTA
		{
			get
			{
				return this._VALORAVISTA;
			}
			set
			{
				if ((this._VALORAVISTA != value))
				{
					this.OnVALORAVISTAChanging(value);
					this.SendPropertyChanging();
					this._VALORAVISTA = value;
					this.SendPropertyChanged("VALORAVISTA");
					this.OnVALORAVISTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALORAPRAZO", DbType="Decimal(15,4)")]
		public System.Nullable<decimal> VALORAPRAZO
		{
			get
			{
				return this._VALORAPRAZO;
			}
			set
			{
				if ((this._VALORAPRAZO != value))
				{
					this.OnVALORAPRAZOChanging(value);
					this.SendPropertyChanging();
					this._VALORAPRAZO = value;
					this.SendPropertyChanged("VALORAPRAZO");
					this.OnVALORAPRAZOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIMEIROVENCIMENTO", DbType="DateTime2")]
		public System.Nullable<System.DateTime> PRIMEIROVENCIMENTO
		{
			get
			{
				return this._PRIMEIROVENCIMENTO;
			}
			set
			{
				if ((this._PRIMEIROVENCIMENTO != value))
				{
					this.OnPRIMEIROVENCIMENTOChanging(value);
					this.SendPropertyChanging();
					this._PRIMEIROVENCIMENTO = value;
					this.SendPropertyChanged("PRIMEIROVENCIMENTO");
					this.OnPRIMEIROVENCIMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTERVALODIAS", DbType="SmallInt")]
		public System.Nullable<short> INTERVALODIAS
		{
			get
			{
				return this._INTERVALODIAS;
			}
			set
			{
				if ((this._INTERVALODIAS != value))
				{
					this.OnINTERVALODIASChanging(value);
					this.SendPropertyChanging();
					this._INTERVALODIAS = value;
					this.SendPropertyChanged("INTERVALODIAS");
					this.OnINTERVALODIASChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPOVALORDESPESA", DbType="SmallInt")]
		public System.Nullable<short> TIPOVALORDESPESA
		{
			get
			{
				return this._TIPOVALORDESPESA;
			}
			set
			{
				if ((this._TIPOVALORDESPESA != value))
				{
					this.OnTIPOVALORDESPESAChanging(value);
					this.SendPropertyChanging();
					this._TIPOVALORDESPESA = value;
					this.SendPropertyChanged("TIPOVALORDESPESA");
					this.OnTIPOVALORDESPESAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPOVALORREEMBOLSO", DbType="SmallInt")]
		public System.Nullable<short> TIPOVALORREEMBOLSO
		{
			get
			{
				return this._TIPOVALORREEMBOLSO;
			}
			set
			{
				if ((this._TIPOVALORREEMBOLSO != value))
				{
					this.OnTIPOVALORREEMBOLSOChanging(value);
					this.SendPropertyChanging();
					this._TIPOVALORREEMBOLSO = value;
					this.SendPropertyChanged("TIPOVALORREEMBOLSO");
					this.OnTIPOVALORREEMBOLSOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPARAMFIN", DbType="Int")]
		public System.Nullable<int> IDPARAMFIN
		{
			get
			{
				return this._IDPARAMFIN;
			}
			set
			{
				if ((this._IDPARAMFIN != value))
				{
					this.OnIDPARAMFINChanging(value);
					this.SendPropertyChanging();
					this._IDPARAMFIN = value;
					this.SendPropertyChanged("IDPARAMFIN");
					this.OnIDPARAMFINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COD_PESS_EMPR", DbType="Int")]
		public System.Nullable<int> COD_PESS_EMPR
		{
			get
			{
				return this._COD_PESS_EMPR;
			}
			set
			{
				if ((this._COD_PESS_EMPR != value))
				{
					this.OnCOD_PESS_EMPRChanging(value);
					this.SendPropertyChanging();
					this._COD_PESS_EMPR = value;
					this.SendPropertyChanged("COD_PESS_EMPR");
					this.OnCOD_PESS_EMPRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUM_UNID", DbType="VarChar(6)")]
		public string NUM_UNID
		{
			get
			{
				return this._NUM_UNID;
			}
			set
			{
				if ((this._NUM_UNID != value))
				{
					this.OnNUM_UNIDChanging(value);
					this.SendPropertyChanging();
					this._NUM_UNID = value;
					this.SendPropertyChanged("NUM_UNID");
					this.OnNUM_UNIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUM_SUB_UNID", DbType="VarChar(6)")]
		public string NUM_SUB_UNID
		{
			get
			{
				return this._NUM_SUB_UNID;
			}
			set
			{
				if ((this._NUM_SUB_UNID != value))
				{
					this.OnNUM_SUB_UNIDChanging(value);
					this.SendPropertyChanging();
					this._NUM_SUB_UNID = value;
					this.SendPropertyChanged("NUM_SUB_UNID");
					this.OnNUM_SUB_UNIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTERVALODIASREEMBOLSO", DbType="Int")]
		public System.Nullable<int> INTERVALODIASREEMBOLSO
		{
			get
			{
				return this._INTERVALODIASREEMBOLSO;
			}
			set
			{
				if ((this._INTERVALODIASREEMBOLSO != value))
				{
					this.OnINTERVALODIASREEMBOLSOChanging(value);
					this.SendPropertyChanging();
					this._INTERVALODIASREEMBOLSO = value;
					this.SendPropertyChanged("INTERVALODIASREEMBOLSO");
					this.OnINTERVALODIASREEMBOLSOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANOEXERCICIO", DbType="Int")]
		public System.Nullable<int> ANOEXERCICIO
		{
			get
			{
				return this._ANOEXERCICIO;
			}
			set
			{
				if ((this._ANOEXERCICIO != value))
				{
					this.OnANOEXERCICIOChanging(value);
					this.SendPropertyChanging();
					this._ANOEXERCICIO = value;
					this.SendPropertyChanged("ANOEXERCICIO");
					this.OnANOEXERCICIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODSEGURO", DbType="Int")]
		public System.Nullable<int> CODSEGURO
		{
			get
			{
				return this._CODSEGURO;
			}
			set
			{
				if ((this._CODSEGURO != value))
				{
					this.OnCODSEGUROChanging(value);
					this.SendPropertyChanging();
					this._CODSEGURO = value;
					this.SendPropertyChanged("CODSEGURO");
					this.OnCODSEGUROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIMEIROVCTOREEMBOLSO", DbType="DateTime2")]
		public System.Nullable<System.DateTime> PRIMEIROVCTOREEMBOLSO
		{
			get
			{
				return this._PRIMEIROVCTOREEMBOLSO;
			}
			set
			{
				if ((this._PRIMEIROVCTOREEMBOLSO != value))
				{
					this.OnPRIMEIROVCTOREEMBOLSOChanging(value);
					this.SendPropertyChanging();
					this._PRIMEIROVCTOREEMBOLSO = value;
					this.SendPropertyChanged("PRIMEIROVCTOREEMBOLSO");
					this.OnPRIMEIROVCTOREEMBOLSOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERIODICIDADE", DbType="Int NOT NULL")]
		public int PERIODICIDADE
		{
			get
			{
				return this._PERIODICIDADE;
			}
			set
			{
				if ((this._PERIODICIDADE != value))
				{
					this.OnPERIODICIDADEChanging(value);
					this.SendPropertyChanging();
					this._PERIODICIDADE = value;
					this.SendPropertyChanged("PERIODICIDADE");
					this.OnPERIODICIDADEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERIODICIDADEREEMBOLSO", DbType="Int NOT NULL")]
		public int PERIODICIDADEREEMBOLSO
		{
			get
			{
				return this._PERIODICIDADEREEMBOLSO;
			}
			set
			{
				if ((this._PERIODICIDADEREEMBOLSO != value))
				{
					this.OnPERIODICIDADEREEMBOLSOChanging(value);
					this.SendPropertyChanging();
					this._PERIODICIDADEREEMBOLSO = value;
					this.SendPropertyChanged("PERIODICIDADEREEMBOLSO");
					this.OnPERIODICIDADEREEMBOLSOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
