<?xml version="1.0" encoding="utf-8"?><Database Name="BDTRANSF" Class="DespesasImoveisDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DEVBD;Initial Catalog=BDTRANSF;Integrated Security=True" SettingsObjectName="Corpore_Imoveis.Properties.Settings" SettingsPropertyName="BDTRANSFConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblCargaImoveisDadosCompletosDespesas20210531" Member="tblCargaImoveisDadosCompletosDespesas20210531s">
    <Type Name="tblCargaImoveisDadosCompletosDespesas20210531">
      <Column Name="EMGEA_ID" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="EMGEA_DISPONIVEL_RESALE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="EMGEA_VENDIDO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="EMGEA_NumContrato" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="EMGEA_Tipo_de_Imovel" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="EMGEA_UF" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="EMGEA_CIDADE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="EMGEA_IPTU" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="EMGEA_CONDOMINIO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NÚMERO_OFICIO_JUSTIFICATIVA" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="EMITIDA_MATRICULA_ATUALIZADA" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TTTUL_EMGEA" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TITUL_CEF" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TITUL_MUTUARIO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ARREMATADA" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="EMGEA_COMPRA_VENDA_ALIENACAO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DOSSIES_RECEBIDO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DOSSIES_MATRICULA" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DOSSIES_EMGEA" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DOSSIES_CEF" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DOSSIES_LAUDO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DOSSIES_DATA_LAUDO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DOSSIES_DESPESA" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DOSSIES_GERAL" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DOSSIES_DIGITALIZADO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DOSSIES_TRATADO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DOSSIES_FTP" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IPTU" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IPTU_NUM_REGISTRO_IMOVEIS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IPTU_MATRiCULA_REGISTRO_IMOVEIS" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IPTU_OBTIDO_IPTU_2021" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IPTU_ISENTO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SEM_COBRANCA_IPTU" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IPTU_QUITADO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="EMISSAO_IPTU_2021" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="VALOR_TOTAL_IPTU_2021" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DESCONTO_TX" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DESCONTO_RS" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="VALOR_TOTAL_C__DESCONTO" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="VENCIMENTO_CONTA_ÚNICA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="N_DE_PARCELAS" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PARC_01" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PARC_02" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PARC_03" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PARC_04" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PARC_05" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PARC_06" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PARC_07" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PARC_08" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PARC_09" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PARC_10" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PARC_11" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PARC_12" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="CND" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="EXTRATO_DIVIDA" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DIVIDA_ATIVA__AJUIZADAS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="VALOR_TOTAL_DIVIDA" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PERIODO_DA_DIVIDA" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DATA_ATUALIZACAO_DIVIDA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DEBITO_ANTERIOR_A_2016" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="VALOR_DO_DEB_ANT_2016" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="AJUIZADOS___EXECUTADOS" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="VALOR_DEB_AJ_EXEC" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PRESCRICAO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="VALOR_DEBITO_PRESC" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="VALOR_LIQ_DO_DEBITO" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="REFIS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PREVISAO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="VALOR_À_VISTA" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="VALOR_DA_PARCELA_EM_12x" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="TOTAL_DO_DEBITO_EM_12x" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="VALOR_DA_PARCELA_EM_24X" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="TOTAL_DO_DEBITO_EM_24X" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="VALOR_DA_PARCELA_EM_36X" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="TOTAL_DO_DEBITO_EM_36X" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="N_DE_PARCELAS1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="VALOR_PARCELA" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="VALOR_TOTAL_PARCELADO" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PGTO_DEBITOS" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="VALOR_PGTO_DEBITO" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PAGAMENTO_04_2021_IPTU_2021" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="VALOR_PGTO_04_2021" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="SOLICITADO_PROCURACAO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ENVIADA_PROCURACAO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CONSULTA_CPF_CNPJ" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DIVERGENCIA_MATRICIPTU_BASE_EMGEA" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BASE_CALC_CONDOMINIO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="INF_APURADA" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SOLICITADO_MATRICULA_ATUALIZADA" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="RECUSA_DE_INFORMACAO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SOLICITADO_DOCUMENTOS_COMPROBATORIOS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SEM_RETORNO_CONDOMINIO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SEM_CONTATO_CONDOMINIO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CONTATO_CONDOMINIO_SEM_SUCESSO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CONDOMINIO_SEM_DOCUMENTACAO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SEM_CONDOMINIO_FORA_DA_BASE_DE_CALCULO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="INFORMACOES_DIVERGENTES" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="INFORMACAO_UNIDADE_ARREMATADA" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AREA_DE_RISCO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="INTERDITADOS___DEMOLIDOS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TITUL_EMGEA" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TITUL_CEF1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NOME_DO_CONDOMINIO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="INFORMACAO_TAX_COND_EM_DIA" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="VALOR_TAX_CONDOMINIAL_ESTIMATIVA" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="EXTRATO_DA_DIVIDA_CONDOMINIAL" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="VALOR_TOTAL_DA_DIVIDA_CONDOMINIAL" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DATA_DA_ATUALIZACAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MESES" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VALOR_ESTIMADO_DE_REAJUSTE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="INCLUSAO_DE_10TX_S__AJUIZAMENTO" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="VALOR_ESTIMADO_ATUALIZADO" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PGTO_DIVIDA_CONDOMINIAL" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="VALOR_PGTO_DIVIDA" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DESCONTO_NEGOCIACAO_DIVIDA" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="AJUIZADAS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DIA_VCTO_PADRAO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PGTO_OCUPANTE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PGTO_OUT_2020_" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="VALOR_PGTO_OUT_2020" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PGTO_NOV_2020_" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="VALOR_PGTO_NOV_2020" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PGTO_DEZ_2020_" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="VALOR_PGTO_DEZ_2020" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PGTO_JAN_2021" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="VALOR_PGTO_JAN_2021" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PGTO_FEV_2021" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="VALOR_PGTO_FEV_2021" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PGTO_MAR_2021" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="VALOR_PGTO_MAR_2021" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PGTO_ABR_2021" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="VALOR_PGTO_ABR_2021" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="CNPJ_CONDOMINIO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="N_CNPJ_CONDOMINIO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CONDOMINIO_INFORMAL_RATEIO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CONTATO_DIRETO_CONDOMINIO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NOME_SINDICO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TELEFONE_SINDICO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="EMAIL_SINDICO_OU_CONDOMINIO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CONTATO_ADMINISTRADORA" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NOME_ADMINISTRADORA" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CNPJ_ADMINISTRADORA" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BAIRRO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CEP" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="VALOR_DE_AVALIACAO" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="OCUPACAO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CHAVES" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[OBS:]" Member="OBS_" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FOTOS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
</Database>