#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corpore_Imoveis
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BDTRANSF")]
	public partial class DespesasImoveisDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DespesasImoveisDataContext() : 
				base(global::Corpore_Imoveis.Properties.Settings.Default.BDTRANSFConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DespesasImoveisDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DespesasImoveisDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DespesasImoveisDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DespesasImoveisDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblCargaImoveisDadosCompletosDespesas20210531> tblCargaImoveisDadosCompletosDespesas20210531s
		{
			get
			{
				return this.GetTable<tblCargaImoveisDadosCompletosDespesas20210531>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCargaImoveisDadosCompletosDespesas20210531")]
	public partial class tblCargaImoveisDadosCompletosDespesas20210531
	{
		
		private System.Nullable<double> _EMGEA_ID;
		
		private string _EMGEA_DISPONIVEL_RESALE;
		
		private string _EMGEA_VENDIDO;
		
		private System.Nullable<double> _EMGEA_NumContrato;
		
		private string _EMGEA_Tipo_de_Imovel;
		
		private string _EMGEA_UF;
		
		private string _EMGEA_CIDADE;
		
		private string _EMGEA_IPTU;
		
		private string _EMGEA_CONDOMINIO;
		
		private string _NÚMERO_OFICIO_JUSTIFICATIVA;
		
		private string _EMITIDA_MATRICULA_ATUALIZADA;
		
		private string _TTTUL_EMGEA;
		
		private string _TITUL_CEF;
		
		private string _TITUL_MUTUARIO;
		
		private string _ARREMATADA;
		
		private string _EMGEA_COMPRA_VENDA_ALIENACAO;
		
		private string _DOSSIES_RECEBIDO;
		
		private string _DOSSIES_MATRICULA;
		
		private string _DOSSIES_EMGEA;
		
		private string _DOSSIES_CEF;
		
		private string _DOSSIES_LAUDO;
		
		private string _DOSSIES_DATA_LAUDO;
		
		private string _DOSSIES_DESPESA;
		
		private string _DOSSIES_GERAL;
		
		private string _DOSSIES_DIGITALIZADO;
		
		private string _DOSSIES_TRATADO;
		
		private string _DOSSIES_FTP;
		
		private string _IPTU;
		
		private string _IPTU_NUM_REGISTRO_IMOVEIS;
		
		private System.Nullable<double> _IPTU_MATRiCULA_REGISTRO_IMOVEIS;
		
		private string _IPTU_OBTIDO_IPTU_2021;
		
		private string _IPTU_ISENTO;
		
		private string _SEM_COBRANCA_IPTU;
		
		private string _IPTU_QUITADO;
		
		private string _EMISSAO_IPTU_2021;
		
		private System.Nullable<decimal> _VALOR_TOTAL_IPTU_2021;
		
		private System.Nullable<double> _DESCONTO_TX;
		
		private System.Nullable<decimal> _DESCONTO_RS;
		
		private System.Nullable<decimal> _VALOR_TOTAL_C__DESCONTO;
		
		private System.Nullable<System.DateTime> _VENCIMENTO_CONTA_ÚNICA;
		
		private System.Nullable<double> _N_DE_PARCELAS;
		
		private System.Nullable<decimal> _PARC_01;
		
		private System.Nullable<decimal> _PARC_02;
		
		private System.Nullable<decimal> _PARC_03;
		
		private System.Nullable<decimal> _PARC_04;
		
		private System.Nullable<decimal> _PARC_05;
		
		private System.Nullable<decimal> _PARC_06;
		
		private System.Nullable<decimal> _PARC_07;
		
		private System.Nullable<decimal> _PARC_08;
		
		private System.Nullable<decimal> _PARC_09;
		
		private System.Nullable<decimal> _PARC_10;
		
		private System.Nullable<decimal> _PARC_11;
		
		private System.Nullable<decimal> _PARC_12;
		
		private string _CND;
		
		private string _EXTRATO_DIVIDA;
		
		private string _DIVIDA_ATIVA__AJUIZADAS;
		
		private System.Nullable<decimal> _VALOR_TOTAL_DIVIDA;
		
		private string _PERIODO_DA_DIVIDA;
		
		private System.Nullable<System.DateTime> _DATA_ATUALIZACAO_DIVIDA;
		
		private System.Nullable<decimal> _DEBITO_ANTERIOR_A_2016;
		
		private System.Nullable<decimal> _VALOR_DO_DEB_ANT_2016;
		
		private System.Nullable<decimal> _AJUIZADOS___EXECUTADOS;
		
		private System.Nullable<decimal> _VALOR_DEB_AJ_EXEC;
		
		private string _PRESCRICAO;
		
		private System.Nullable<decimal> _VALOR_DEBITO_PRESC;
		
		private System.Nullable<decimal> _VALOR_LIQ_DO_DEBITO;
		
		private string _REFIS;
		
		private string _PREVISAO;
		
		private System.Nullable<decimal> _VALOR_À_VISTA;
		
		private System.Nullable<decimal> _VALOR_DA_PARCELA_EM_12x;
		
		private System.Nullable<decimal> _TOTAL_DO_DEBITO_EM_12x;
		
		private System.Nullable<decimal> _VALOR_DA_PARCELA_EM_24X;
		
		private System.Nullable<decimal> _TOTAL_DO_DEBITO_EM_24X;
		
		private System.Nullable<decimal> _VALOR_DA_PARCELA_EM_36X;
		
		private System.Nullable<decimal> _TOTAL_DO_DEBITO_EM_36X;
		
		private string _N_DE_PARCELAS1;
		
		private System.Nullable<decimal> _VALOR_PARCELA;
		
		private System.Nullable<decimal> _VALOR_TOTAL_PARCELADO;
		
		private System.Nullable<decimal> _PGTO_DEBITOS;
		
		private System.Nullable<decimal> _VALOR_PGTO_DEBITO;
		
		private string _PAGAMENTO_04_2021_IPTU_2021;
		
		private System.Nullable<decimal> _VALOR_PGTO_04_2021;
		
		private string _SOLICITADO_PROCURACAO;
		
		private string _ENVIADA_PROCURACAO;
		
		private string _CONSULTA_CPF_CNPJ;
		
		private string _DIVERGENCIA_MATRICIPTU_BASE_EMGEA;
		
		private string _BASE_CALC_CONDOMINIO;
		
		private string _INF_APURADA;
		
		private string _SOLICITADO_MATRICULA_ATUALIZADA;
		
		private string _RECUSA_DE_INFORMACAO;
		
		private string _SOLICITADO_DOCUMENTOS_COMPROBATORIOS;
		
		private string _SEM_RETORNO_CONDOMINIO;
		
		private string _SEM_CONTATO_CONDOMINIO;
		
		private string _CONTATO_CONDOMINIO_SEM_SUCESSO;
		
		private string _CONDOMINIO_SEM_DOCUMENTACAO;
		
		private string _SEM_CONDOMINIO_FORA_DA_BASE_DE_CALCULO;
		
		private string _INFORMACOES_DIVERGENTES;
		
		private string _INFORMACAO_UNIDADE_ARREMATADA;
		
		private string _AREA_DE_RISCO;
		
		private string _INTERDITADOS___DEMOLIDOS;
		
		private string _TITUL_EMGEA;
		
		private string _TITUL_CEF1;
		
		private string _NOME_DO_CONDOMINIO;
		
		private string _INFORMACAO_TAX_COND_EM_DIA;
		
		private System.Nullable<decimal> _VALOR_TAX_CONDOMINIAL_ESTIMATIVA;
		
		private string _EXTRATO_DA_DIVIDA_CONDOMINIAL;
		
		private System.Nullable<decimal> _VALOR_TOTAL_DA_DIVIDA_CONDOMINIAL;
		
		private System.Nullable<System.DateTime> _DATA_DA_ATUALIZACAO;
		
		private System.Nullable<System.DateTime> _MESES;
		
		private System.Nullable<System.DateTime> _VALOR_ESTIMADO_DE_REAJUSTE;
		
		private System.Nullable<decimal> _INCLUSAO_DE_10TX_S__AJUIZAMENTO;
		
		private System.Nullable<decimal> _VALOR_ESTIMADO_ATUALIZADO;
		
		private string _PGTO_DIVIDA_CONDOMINIAL;
		
		private System.Nullable<decimal> _VALOR_PGTO_DIVIDA;
		
		private System.Nullable<decimal> _DESCONTO_NEGOCIACAO_DIVIDA;
		
		private string _AJUIZADAS;
		
		private System.Nullable<double> _DIA_VCTO_PADRAO;
		
		private string _PGTO_OCUPANTE;
		
		private string _PGTO_OUT_2020_;
		
		private System.Nullable<decimal> _VALOR_PGTO_OUT_2020;
		
		private string _PGTO_NOV_2020_;
		
		private System.Nullable<decimal> _VALOR_PGTO_NOV_2020;
		
		private string _PGTO_DEZ_2020_;
		
		private System.Nullable<decimal> _VALOR_PGTO_DEZ_2020;
		
		private string _PGTO_JAN_2021;
		
		private System.Nullable<decimal> _VALOR_PGTO_JAN_2021;
		
		private string _PGTO_FEV_2021;
		
		private System.Nullable<decimal> _VALOR_PGTO_FEV_2021;
		
		private string _PGTO_MAR_2021;
		
		private System.Nullable<decimal> _VALOR_PGTO_MAR_2021;
		
		private string _PGTO_ABR_2021;
		
		private System.Nullable<decimal> _VALOR_PGTO_ABR_2021;
		
		private string _CNPJ_CONDOMINIO;
		
		private string _N_CNPJ_CONDOMINIO;
		
		private System.Nullable<double> _CONDOMINIO_INFORMAL_RATEIO;
		
		private string _CONTATO_DIRETO_CONDOMINIO;
		
		private string _NOME_SINDICO;
		
		private string _TELEFONE_SINDICO;
		
		private string _EMAIL_SINDICO_OU_CONDOMINIO;
		
		private string _CONTATO_ADMINISTRADORA;
		
		private string _NOME_ADMINISTRADORA;
		
		private string _CNPJ_ADMINISTRADORA;
		
		private string _BAIRRO;
		
		private string _CEP;
		
		private System.Nullable<decimal> _VALOR_DE_AVALIACAO;
		
		private string _OCUPACAO;
		
		private string _CHAVES;
		
		private string _OBS_;
		
		private string _FOTOS;
		
		public tblCargaImoveisDadosCompletosDespesas20210531()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMGEA_ID", DbType="Float")]
		public System.Nullable<double> EMGEA_ID
		{
			get
			{
				return this._EMGEA_ID;
			}
			set
			{
				if ((this._EMGEA_ID != value))
				{
					this._EMGEA_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMGEA_DISPONIVEL_RESALE", DbType="NVarChar(255)")]
		public string EMGEA_DISPONIVEL_RESALE
		{
			get
			{
				return this._EMGEA_DISPONIVEL_RESALE;
			}
			set
			{
				if ((this._EMGEA_DISPONIVEL_RESALE != value))
				{
					this._EMGEA_DISPONIVEL_RESALE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMGEA_VENDIDO", DbType="NVarChar(255)")]
		public string EMGEA_VENDIDO
		{
			get
			{
				return this._EMGEA_VENDIDO;
			}
			set
			{
				if ((this._EMGEA_VENDIDO != value))
				{
					this._EMGEA_VENDIDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMGEA_NumContrato", DbType="Float")]
		public System.Nullable<double> EMGEA_NumContrato
		{
			get
			{
				return this._EMGEA_NumContrato;
			}
			set
			{
				if ((this._EMGEA_NumContrato != value))
				{
					this._EMGEA_NumContrato = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMGEA_Tipo_de_Imovel", DbType="NVarChar(255)")]
		public string EMGEA_Tipo_de_Imovel
		{
			get
			{
				return this._EMGEA_Tipo_de_Imovel;
			}
			set
			{
				if ((this._EMGEA_Tipo_de_Imovel != value))
				{
					this._EMGEA_Tipo_de_Imovel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMGEA_UF", DbType="NVarChar(255)")]
		public string EMGEA_UF
		{
			get
			{
				return this._EMGEA_UF;
			}
			set
			{
				if ((this._EMGEA_UF != value))
				{
					this._EMGEA_UF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMGEA_CIDADE", DbType="NVarChar(255)")]
		public string EMGEA_CIDADE
		{
			get
			{
				return this._EMGEA_CIDADE;
			}
			set
			{
				if ((this._EMGEA_CIDADE != value))
				{
					this._EMGEA_CIDADE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMGEA_IPTU", DbType="NVarChar(255)")]
		public string EMGEA_IPTU
		{
			get
			{
				return this._EMGEA_IPTU;
			}
			set
			{
				if ((this._EMGEA_IPTU != value))
				{
					this._EMGEA_IPTU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMGEA_CONDOMINIO", DbType="NVarChar(255)")]
		public string EMGEA_CONDOMINIO
		{
			get
			{
				return this._EMGEA_CONDOMINIO;
			}
			set
			{
				if ((this._EMGEA_CONDOMINIO != value))
				{
					this._EMGEA_CONDOMINIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NÚMERO_OFICIO_JUSTIFICATIVA", DbType="NVarChar(255)")]
		public string NÚMERO_OFICIO_JUSTIFICATIVA
		{
			get
			{
				return this._NÚMERO_OFICIO_JUSTIFICATIVA;
			}
			set
			{
				if ((this._NÚMERO_OFICIO_JUSTIFICATIVA != value))
				{
					this._NÚMERO_OFICIO_JUSTIFICATIVA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMITIDA_MATRICULA_ATUALIZADA", DbType="NVarChar(255)")]
		public string EMITIDA_MATRICULA_ATUALIZADA
		{
			get
			{
				return this._EMITIDA_MATRICULA_ATUALIZADA;
			}
			set
			{
				if ((this._EMITIDA_MATRICULA_ATUALIZADA != value))
				{
					this._EMITIDA_MATRICULA_ATUALIZADA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TTTUL_EMGEA", DbType="NVarChar(255)")]
		public string TTTUL_EMGEA
		{
			get
			{
				return this._TTTUL_EMGEA;
			}
			set
			{
				if ((this._TTTUL_EMGEA != value))
				{
					this._TTTUL_EMGEA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITUL_CEF", DbType="NVarChar(255)")]
		public string TITUL_CEF
		{
			get
			{
				return this._TITUL_CEF;
			}
			set
			{
				if ((this._TITUL_CEF != value))
				{
					this._TITUL_CEF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITUL_MUTUARIO", DbType="NVarChar(255)")]
		public string TITUL_MUTUARIO
		{
			get
			{
				return this._TITUL_MUTUARIO;
			}
			set
			{
				if ((this._TITUL_MUTUARIO != value))
				{
					this._TITUL_MUTUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARREMATADA", DbType="NVarChar(255)")]
		public string ARREMATADA
		{
			get
			{
				return this._ARREMATADA;
			}
			set
			{
				if ((this._ARREMATADA != value))
				{
					this._ARREMATADA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMGEA_COMPRA_VENDA_ALIENACAO", DbType="NVarChar(255)")]
		public string EMGEA_COMPRA_VENDA_ALIENACAO
		{
			get
			{
				return this._EMGEA_COMPRA_VENDA_ALIENACAO;
			}
			set
			{
				if ((this._EMGEA_COMPRA_VENDA_ALIENACAO != value))
				{
					this._EMGEA_COMPRA_VENDA_ALIENACAO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOSSIES_RECEBIDO", DbType="NVarChar(255)")]
		public string DOSSIES_RECEBIDO
		{
			get
			{
				return this._DOSSIES_RECEBIDO;
			}
			set
			{
				if ((this._DOSSIES_RECEBIDO != value))
				{
					this._DOSSIES_RECEBIDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOSSIES_MATRICULA", DbType="NVarChar(255)")]
		public string DOSSIES_MATRICULA
		{
			get
			{
				return this._DOSSIES_MATRICULA;
			}
			set
			{
				if ((this._DOSSIES_MATRICULA != value))
				{
					this._DOSSIES_MATRICULA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOSSIES_EMGEA", DbType="NVarChar(255)")]
		public string DOSSIES_EMGEA
		{
			get
			{
				return this._DOSSIES_EMGEA;
			}
			set
			{
				if ((this._DOSSIES_EMGEA != value))
				{
					this._DOSSIES_EMGEA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOSSIES_CEF", DbType="NVarChar(255)")]
		public string DOSSIES_CEF
		{
			get
			{
				return this._DOSSIES_CEF;
			}
			set
			{
				if ((this._DOSSIES_CEF != value))
				{
					this._DOSSIES_CEF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOSSIES_LAUDO", DbType="NVarChar(255)")]
		public string DOSSIES_LAUDO
		{
			get
			{
				return this._DOSSIES_LAUDO;
			}
			set
			{
				if ((this._DOSSIES_LAUDO != value))
				{
					this._DOSSIES_LAUDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOSSIES_DATA_LAUDO", DbType="NVarChar(255)")]
		public string DOSSIES_DATA_LAUDO
		{
			get
			{
				return this._DOSSIES_DATA_LAUDO;
			}
			set
			{
				if ((this._DOSSIES_DATA_LAUDO != value))
				{
					this._DOSSIES_DATA_LAUDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOSSIES_DESPESA", DbType="NVarChar(255)")]
		public string DOSSIES_DESPESA
		{
			get
			{
				return this._DOSSIES_DESPESA;
			}
			set
			{
				if ((this._DOSSIES_DESPESA != value))
				{
					this._DOSSIES_DESPESA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOSSIES_GERAL", DbType="NVarChar(255)")]
		public string DOSSIES_GERAL
		{
			get
			{
				return this._DOSSIES_GERAL;
			}
			set
			{
				if ((this._DOSSIES_GERAL != value))
				{
					this._DOSSIES_GERAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOSSIES_DIGITALIZADO", DbType="NVarChar(255)")]
		public string DOSSIES_DIGITALIZADO
		{
			get
			{
				return this._DOSSIES_DIGITALIZADO;
			}
			set
			{
				if ((this._DOSSIES_DIGITALIZADO != value))
				{
					this._DOSSIES_DIGITALIZADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOSSIES_TRATADO", DbType="NVarChar(255)")]
		public string DOSSIES_TRATADO
		{
			get
			{
				return this._DOSSIES_TRATADO;
			}
			set
			{
				if ((this._DOSSIES_TRATADO != value))
				{
					this._DOSSIES_TRATADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOSSIES_FTP", DbType="NVarChar(255)")]
		public string DOSSIES_FTP
		{
			get
			{
				return this._DOSSIES_FTP;
			}
			set
			{
				if ((this._DOSSIES_FTP != value))
				{
					this._DOSSIES_FTP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPTU", DbType="NVarChar(255)")]
		public string IPTU
		{
			get
			{
				return this._IPTU;
			}
			set
			{
				if ((this._IPTU != value))
				{
					this._IPTU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPTU_NUM_REGISTRO_IMOVEIS", DbType="NVarChar(255)")]
		public string IPTU_NUM_REGISTRO_IMOVEIS
		{
			get
			{
				return this._IPTU_NUM_REGISTRO_IMOVEIS;
			}
			set
			{
				if ((this._IPTU_NUM_REGISTRO_IMOVEIS != value))
				{
					this._IPTU_NUM_REGISTRO_IMOVEIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPTU_MATRiCULA_REGISTRO_IMOVEIS", DbType="Float")]
		public System.Nullable<double> IPTU_MATRiCULA_REGISTRO_IMOVEIS
		{
			get
			{
				return this._IPTU_MATRiCULA_REGISTRO_IMOVEIS;
			}
			set
			{
				if ((this._IPTU_MATRiCULA_REGISTRO_IMOVEIS != value))
				{
					this._IPTU_MATRiCULA_REGISTRO_IMOVEIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPTU_OBTIDO_IPTU_2021", DbType="NVarChar(255)")]
		public string IPTU_OBTIDO_IPTU_2021
		{
			get
			{
				return this._IPTU_OBTIDO_IPTU_2021;
			}
			set
			{
				if ((this._IPTU_OBTIDO_IPTU_2021 != value))
				{
					this._IPTU_OBTIDO_IPTU_2021 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPTU_ISENTO", DbType="NVarChar(255)")]
		public string IPTU_ISENTO
		{
			get
			{
				return this._IPTU_ISENTO;
			}
			set
			{
				if ((this._IPTU_ISENTO != value))
				{
					this._IPTU_ISENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEM_COBRANCA_IPTU", DbType="NVarChar(255)")]
		public string SEM_COBRANCA_IPTU
		{
			get
			{
				return this._SEM_COBRANCA_IPTU;
			}
			set
			{
				if ((this._SEM_COBRANCA_IPTU != value))
				{
					this._SEM_COBRANCA_IPTU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPTU_QUITADO", DbType="NVarChar(255)")]
		public string IPTU_QUITADO
		{
			get
			{
				return this._IPTU_QUITADO;
			}
			set
			{
				if ((this._IPTU_QUITADO != value))
				{
					this._IPTU_QUITADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMISSAO_IPTU_2021", DbType="NVarChar(255)")]
		public string EMISSAO_IPTU_2021
		{
			get
			{
				return this._EMISSAO_IPTU_2021;
			}
			set
			{
				if ((this._EMISSAO_IPTU_2021 != value))
				{
					this._EMISSAO_IPTU_2021 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_TOTAL_IPTU_2021", DbType="Money")]
		public System.Nullable<decimal> VALOR_TOTAL_IPTU_2021
		{
			get
			{
				return this._VALOR_TOTAL_IPTU_2021;
			}
			set
			{
				if ((this._VALOR_TOTAL_IPTU_2021 != value))
				{
					this._VALOR_TOTAL_IPTU_2021 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCONTO_TX", DbType="Float")]
		public System.Nullable<double> DESCONTO_TX
		{
			get
			{
				return this._DESCONTO_TX;
			}
			set
			{
				if ((this._DESCONTO_TX != value))
				{
					this._DESCONTO_TX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCONTO_RS", DbType="Money")]
		public System.Nullable<decimal> DESCONTO_RS
		{
			get
			{
				return this._DESCONTO_RS;
			}
			set
			{
				if ((this._DESCONTO_RS != value))
				{
					this._DESCONTO_RS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_TOTAL_C__DESCONTO", DbType="Money")]
		public System.Nullable<decimal> VALOR_TOTAL_C__DESCONTO
		{
			get
			{
				return this._VALOR_TOTAL_C__DESCONTO;
			}
			set
			{
				if ((this._VALOR_TOTAL_C__DESCONTO != value))
				{
					this._VALOR_TOTAL_C__DESCONTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VENCIMENTO_CONTA_ÚNICA", DbType="DateTime")]
		public System.Nullable<System.DateTime> VENCIMENTO_CONTA_ÚNICA
		{
			get
			{
				return this._VENCIMENTO_CONTA_ÚNICA;
			}
			set
			{
				if ((this._VENCIMENTO_CONTA_ÚNICA != value))
				{
					this._VENCIMENTO_CONTA_ÚNICA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_DE_PARCELAS", DbType="Float")]
		public System.Nullable<double> N_DE_PARCELAS
		{
			get
			{
				return this._N_DE_PARCELAS;
			}
			set
			{
				if ((this._N_DE_PARCELAS != value))
				{
					this._N_DE_PARCELAS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARC_01", DbType="Money")]
		public System.Nullable<decimal> PARC_01
		{
			get
			{
				return this._PARC_01;
			}
			set
			{
				if ((this._PARC_01 != value))
				{
					this._PARC_01 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARC_02", DbType="Money")]
		public System.Nullable<decimal> PARC_02
		{
			get
			{
				return this._PARC_02;
			}
			set
			{
				if ((this._PARC_02 != value))
				{
					this._PARC_02 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARC_03", DbType="Money")]
		public System.Nullable<decimal> PARC_03
		{
			get
			{
				return this._PARC_03;
			}
			set
			{
				if ((this._PARC_03 != value))
				{
					this._PARC_03 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARC_04", DbType="Money")]
		public System.Nullable<decimal> PARC_04
		{
			get
			{
				return this._PARC_04;
			}
			set
			{
				if ((this._PARC_04 != value))
				{
					this._PARC_04 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARC_05", DbType="Money")]
		public System.Nullable<decimal> PARC_05
		{
			get
			{
				return this._PARC_05;
			}
			set
			{
				if ((this._PARC_05 != value))
				{
					this._PARC_05 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARC_06", DbType="Money")]
		public System.Nullable<decimal> PARC_06
		{
			get
			{
				return this._PARC_06;
			}
			set
			{
				if ((this._PARC_06 != value))
				{
					this._PARC_06 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARC_07", DbType="Money")]
		public System.Nullable<decimal> PARC_07
		{
			get
			{
				return this._PARC_07;
			}
			set
			{
				if ((this._PARC_07 != value))
				{
					this._PARC_07 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARC_08", DbType="Money")]
		public System.Nullable<decimal> PARC_08
		{
			get
			{
				return this._PARC_08;
			}
			set
			{
				if ((this._PARC_08 != value))
				{
					this._PARC_08 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARC_09", DbType="Money")]
		public System.Nullable<decimal> PARC_09
		{
			get
			{
				return this._PARC_09;
			}
			set
			{
				if ((this._PARC_09 != value))
				{
					this._PARC_09 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARC_10", DbType="Money")]
		public System.Nullable<decimal> PARC_10
		{
			get
			{
				return this._PARC_10;
			}
			set
			{
				if ((this._PARC_10 != value))
				{
					this._PARC_10 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARC_11", DbType="Money")]
		public System.Nullable<decimal> PARC_11
		{
			get
			{
				return this._PARC_11;
			}
			set
			{
				if ((this._PARC_11 != value))
				{
					this._PARC_11 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARC_12", DbType="Money")]
		public System.Nullable<decimal> PARC_12
		{
			get
			{
				return this._PARC_12;
			}
			set
			{
				if ((this._PARC_12 != value))
				{
					this._PARC_12 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CND", DbType="NVarChar(255)")]
		public string CND
		{
			get
			{
				return this._CND;
			}
			set
			{
				if ((this._CND != value))
				{
					this._CND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXTRATO_DIVIDA", DbType="NVarChar(255)")]
		public string EXTRATO_DIVIDA
		{
			get
			{
				return this._EXTRATO_DIVIDA;
			}
			set
			{
				if ((this._EXTRATO_DIVIDA != value))
				{
					this._EXTRATO_DIVIDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIVIDA_ATIVA__AJUIZADAS", DbType="NVarChar(255)")]
		public string DIVIDA_ATIVA__AJUIZADAS
		{
			get
			{
				return this._DIVIDA_ATIVA__AJUIZADAS;
			}
			set
			{
				if ((this._DIVIDA_ATIVA__AJUIZADAS != value))
				{
					this._DIVIDA_ATIVA__AJUIZADAS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_TOTAL_DIVIDA", DbType="Money")]
		public System.Nullable<decimal> VALOR_TOTAL_DIVIDA
		{
			get
			{
				return this._VALOR_TOTAL_DIVIDA;
			}
			set
			{
				if ((this._VALOR_TOTAL_DIVIDA != value))
				{
					this._VALOR_TOTAL_DIVIDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERIODO_DA_DIVIDA", DbType="NVarChar(255)")]
		public string PERIODO_DA_DIVIDA
		{
			get
			{
				return this._PERIODO_DA_DIVIDA;
			}
			set
			{
				if ((this._PERIODO_DA_DIVIDA != value))
				{
					this._PERIODO_DA_DIVIDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_ATUALIZACAO_DIVIDA", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATA_ATUALIZACAO_DIVIDA
		{
			get
			{
				return this._DATA_ATUALIZACAO_DIVIDA;
			}
			set
			{
				if ((this._DATA_ATUALIZACAO_DIVIDA != value))
				{
					this._DATA_ATUALIZACAO_DIVIDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEBITO_ANTERIOR_A_2016", DbType="Money")]
		public System.Nullable<decimal> DEBITO_ANTERIOR_A_2016
		{
			get
			{
				return this._DEBITO_ANTERIOR_A_2016;
			}
			set
			{
				if ((this._DEBITO_ANTERIOR_A_2016 != value))
				{
					this._DEBITO_ANTERIOR_A_2016 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_DO_DEB_ANT_2016", DbType="Money")]
		public System.Nullable<decimal> VALOR_DO_DEB_ANT_2016
		{
			get
			{
				return this._VALOR_DO_DEB_ANT_2016;
			}
			set
			{
				if ((this._VALOR_DO_DEB_ANT_2016 != value))
				{
					this._VALOR_DO_DEB_ANT_2016 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AJUIZADOS___EXECUTADOS", DbType="Money")]
		public System.Nullable<decimal> AJUIZADOS___EXECUTADOS
		{
			get
			{
				return this._AJUIZADOS___EXECUTADOS;
			}
			set
			{
				if ((this._AJUIZADOS___EXECUTADOS != value))
				{
					this._AJUIZADOS___EXECUTADOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_DEB_AJ_EXEC", DbType="Money")]
		public System.Nullable<decimal> VALOR_DEB_AJ_EXEC
		{
			get
			{
				return this._VALOR_DEB_AJ_EXEC;
			}
			set
			{
				if ((this._VALOR_DEB_AJ_EXEC != value))
				{
					this._VALOR_DEB_AJ_EXEC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRESCRICAO", DbType="NVarChar(255)")]
		public string PRESCRICAO
		{
			get
			{
				return this._PRESCRICAO;
			}
			set
			{
				if ((this._PRESCRICAO != value))
				{
					this._PRESCRICAO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_DEBITO_PRESC", DbType="Money")]
		public System.Nullable<decimal> VALOR_DEBITO_PRESC
		{
			get
			{
				return this._VALOR_DEBITO_PRESC;
			}
			set
			{
				if ((this._VALOR_DEBITO_PRESC != value))
				{
					this._VALOR_DEBITO_PRESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_LIQ_DO_DEBITO", DbType="Money")]
		public System.Nullable<decimal> VALOR_LIQ_DO_DEBITO
		{
			get
			{
				return this._VALOR_LIQ_DO_DEBITO;
			}
			set
			{
				if ((this._VALOR_LIQ_DO_DEBITO != value))
				{
					this._VALOR_LIQ_DO_DEBITO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REFIS", DbType="NVarChar(255)")]
		public string REFIS
		{
			get
			{
				return this._REFIS;
			}
			set
			{
				if ((this._REFIS != value))
				{
					this._REFIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREVISAO", DbType="NVarChar(255)")]
		public string PREVISAO
		{
			get
			{
				return this._PREVISAO;
			}
			set
			{
				if ((this._PREVISAO != value))
				{
					this._PREVISAO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_À_VISTA", DbType="Money")]
		public System.Nullable<decimal> VALOR_À_VISTA
		{
			get
			{
				return this._VALOR_À_VISTA;
			}
			set
			{
				if ((this._VALOR_À_VISTA != value))
				{
					this._VALOR_À_VISTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_DA_PARCELA_EM_12x", DbType="Money")]
		public System.Nullable<decimal> VALOR_DA_PARCELA_EM_12x
		{
			get
			{
				return this._VALOR_DA_PARCELA_EM_12x;
			}
			set
			{
				if ((this._VALOR_DA_PARCELA_EM_12x != value))
				{
					this._VALOR_DA_PARCELA_EM_12x = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_DO_DEBITO_EM_12x", DbType="Money")]
		public System.Nullable<decimal> TOTAL_DO_DEBITO_EM_12x
		{
			get
			{
				return this._TOTAL_DO_DEBITO_EM_12x;
			}
			set
			{
				if ((this._TOTAL_DO_DEBITO_EM_12x != value))
				{
					this._TOTAL_DO_DEBITO_EM_12x = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_DA_PARCELA_EM_24X", DbType="Money")]
		public System.Nullable<decimal> VALOR_DA_PARCELA_EM_24X
		{
			get
			{
				return this._VALOR_DA_PARCELA_EM_24X;
			}
			set
			{
				if ((this._VALOR_DA_PARCELA_EM_24X != value))
				{
					this._VALOR_DA_PARCELA_EM_24X = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_DO_DEBITO_EM_24X", DbType="Money")]
		public System.Nullable<decimal> TOTAL_DO_DEBITO_EM_24X
		{
			get
			{
				return this._TOTAL_DO_DEBITO_EM_24X;
			}
			set
			{
				if ((this._TOTAL_DO_DEBITO_EM_24X != value))
				{
					this._TOTAL_DO_DEBITO_EM_24X = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_DA_PARCELA_EM_36X", DbType="Money")]
		public System.Nullable<decimal> VALOR_DA_PARCELA_EM_36X
		{
			get
			{
				return this._VALOR_DA_PARCELA_EM_36X;
			}
			set
			{
				if ((this._VALOR_DA_PARCELA_EM_36X != value))
				{
					this._VALOR_DA_PARCELA_EM_36X = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_DO_DEBITO_EM_36X", DbType="Money")]
		public System.Nullable<decimal> TOTAL_DO_DEBITO_EM_36X
		{
			get
			{
				return this._TOTAL_DO_DEBITO_EM_36X;
			}
			set
			{
				if ((this._TOTAL_DO_DEBITO_EM_36X != value))
				{
					this._TOTAL_DO_DEBITO_EM_36X = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_DE_PARCELAS1", DbType="NVarChar(255)")]
		public string N_DE_PARCELAS1
		{
			get
			{
				return this._N_DE_PARCELAS1;
			}
			set
			{
				if ((this._N_DE_PARCELAS1 != value))
				{
					this._N_DE_PARCELAS1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_PARCELA", DbType="Money")]
		public System.Nullable<decimal> VALOR_PARCELA
		{
			get
			{
				return this._VALOR_PARCELA;
			}
			set
			{
				if ((this._VALOR_PARCELA != value))
				{
					this._VALOR_PARCELA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_TOTAL_PARCELADO", DbType="Money")]
		public System.Nullable<decimal> VALOR_TOTAL_PARCELADO
		{
			get
			{
				return this._VALOR_TOTAL_PARCELADO;
			}
			set
			{
				if ((this._VALOR_TOTAL_PARCELADO != value))
				{
					this._VALOR_TOTAL_PARCELADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PGTO_DEBITOS", DbType="Money")]
		public System.Nullable<decimal> PGTO_DEBITOS
		{
			get
			{
				return this._PGTO_DEBITOS;
			}
			set
			{
				if ((this._PGTO_DEBITOS != value))
				{
					this._PGTO_DEBITOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_PGTO_DEBITO", DbType="Money")]
		public System.Nullable<decimal> VALOR_PGTO_DEBITO
		{
			get
			{
				return this._VALOR_PGTO_DEBITO;
			}
			set
			{
				if ((this._VALOR_PGTO_DEBITO != value))
				{
					this._VALOR_PGTO_DEBITO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAGAMENTO_04_2021_IPTU_2021", DbType="NVarChar(255)")]
		public string PAGAMENTO_04_2021_IPTU_2021
		{
			get
			{
				return this._PAGAMENTO_04_2021_IPTU_2021;
			}
			set
			{
				if ((this._PAGAMENTO_04_2021_IPTU_2021 != value))
				{
					this._PAGAMENTO_04_2021_IPTU_2021 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_PGTO_04_2021", DbType="Money")]
		public System.Nullable<decimal> VALOR_PGTO_04_2021
		{
			get
			{
				return this._VALOR_PGTO_04_2021;
			}
			set
			{
				if ((this._VALOR_PGTO_04_2021 != value))
				{
					this._VALOR_PGTO_04_2021 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLICITADO_PROCURACAO", DbType="NVarChar(255)")]
		public string SOLICITADO_PROCURACAO
		{
			get
			{
				return this._SOLICITADO_PROCURACAO;
			}
			set
			{
				if ((this._SOLICITADO_PROCURACAO != value))
				{
					this._SOLICITADO_PROCURACAO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENVIADA_PROCURACAO", DbType="NVarChar(255)")]
		public string ENVIADA_PROCURACAO
		{
			get
			{
				return this._ENVIADA_PROCURACAO;
			}
			set
			{
				if ((this._ENVIADA_PROCURACAO != value))
				{
					this._ENVIADA_PROCURACAO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONSULTA_CPF_CNPJ", DbType="NVarChar(255)")]
		public string CONSULTA_CPF_CNPJ
		{
			get
			{
				return this._CONSULTA_CPF_CNPJ;
			}
			set
			{
				if ((this._CONSULTA_CPF_CNPJ != value))
				{
					this._CONSULTA_CPF_CNPJ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIVERGENCIA_MATRICIPTU_BASE_EMGEA", DbType="NVarChar(255)")]
		public string DIVERGENCIA_MATRICIPTU_BASE_EMGEA
		{
			get
			{
				return this._DIVERGENCIA_MATRICIPTU_BASE_EMGEA;
			}
			set
			{
				if ((this._DIVERGENCIA_MATRICIPTU_BASE_EMGEA != value))
				{
					this._DIVERGENCIA_MATRICIPTU_BASE_EMGEA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BASE_CALC_CONDOMINIO", DbType="NVarChar(255)")]
		public string BASE_CALC_CONDOMINIO
		{
			get
			{
				return this._BASE_CALC_CONDOMINIO;
			}
			set
			{
				if ((this._BASE_CALC_CONDOMINIO != value))
				{
					this._BASE_CALC_CONDOMINIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INF_APURADA", DbType="NVarChar(255)")]
		public string INF_APURADA
		{
			get
			{
				return this._INF_APURADA;
			}
			set
			{
				if ((this._INF_APURADA != value))
				{
					this._INF_APURADA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLICITADO_MATRICULA_ATUALIZADA", DbType="NVarChar(255)")]
		public string SOLICITADO_MATRICULA_ATUALIZADA
		{
			get
			{
				return this._SOLICITADO_MATRICULA_ATUALIZADA;
			}
			set
			{
				if ((this._SOLICITADO_MATRICULA_ATUALIZADA != value))
				{
					this._SOLICITADO_MATRICULA_ATUALIZADA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECUSA_DE_INFORMACAO", DbType="NVarChar(255)")]
		public string RECUSA_DE_INFORMACAO
		{
			get
			{
				return this._RECUSA_DE_INFORMACAO;
			}
			set
			{
				if ((this._RECUSA_DE_INFORMACAO != value))
				{
					this._RECUSA_DE_INFORMACAO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLICITADO_DOCUMENTOS_COMPROBATORIOS", DbType="NVarChar(255)")]
		public string SOLICITADO_DOCUMENTOS_COMPROBATORIOS
		{
			get
			{
				return this._SOLICITADO_DOCUMENTOS_COMPROBATORIOS;
			}
			set
			{
				if ((this._SOLICITADO_DOCUMENTOS_COMPROBATORIOS != value))
				{
					this._SOLICITADO_DOCUMENTOS_COMPROBATORIOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEM_RETORNO_CONDOMINIO", DbType="NVarChar(255)")]
		public string SEM_RETORNO_CONDOMINIO
		{
			get
			{
				return this._SEM_RETORNO_CONDOMINIO;
			}
			set
			{
				if ((this._SEM_RETORNO_CONDOMINIO != value))
				{
					this._SEM_RETORNO_CONDOMINIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEM_CONTATO_CONDOMINIO", DbType="NVarChar(255)")]
		public string SEM_CONTATO_CONDOMINIO
		{
			get
			{
				return this._SEM_CONTATO_CONDOMINIO;
			}
			set
			{
				if ((this._SEM_CONTATO_CONDOMINIO != value))
				{
					this._SEM_CONTATO_CONDOMINIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTATO_CONDOMINIO_SEM_SUCESSO", DbType="NVarChar(255)")]
		public string CONTATO_CONDOMINIO_SEM_SUCESSO
		{
			get
			{
				return this._CONTATO_CONDOMINIO_SEM_SUCESSO;
			}
			set
			{
				if ((this._CONTATO_CONDOMINIO_SEM_SUCESSO != value))
				{
					this._CONTATO_CONDOMINIO_SEM_SUCESSO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONDOMINIO_SEM_DOCUMENTACAO", DbType="NVarChar(255)")]
		public string CONDOMINIO_SEM_DOCUMENTACAO
		{
			get
			{
				return this._CONDOMINIO_SEM_DOCUMENTACAO;
			}
			set
			{
				if ((this._CONDOMINIO_SEM_DOCUMENTACAO != value))
				{
					this._CONDOMINIO_SEM_DOCUMENTACAO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEM_CONDOMINIO_FORA_DA_BASE_DE_CALCULO", DbType="NVarChar(255)")]
		public string SEM_CONDOMINIO_FORA_DA_BASE_DE_CALCULO
		{
			get
			{
				return this._SEM_CONDOMINIO_FORA_DA_BASE_DE_CALCULO;
			}
			set
			{
				if ((this._SEM_CONDOMINIO_FORA_DA_BASE_DE_CALCULO != value))
				{
					this._SEM_CONDOMINIO_FORA_DA_BASE_DE_CALCULO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INFORMACOES_DIVERGENTES", DbType="NVarChar(255)")]
		public string INFORMACOES_DIVERGENTES
		{
			get
			{
				return this._INFORMACOES_DIVERGENTES;
			}
			set
			{
				if ((this._INFORMACOES_DIVERGENTES != value))
				{
					this._INFORMACOES_DIVERGENTES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INFORMACAO_UNIDADE_ARREMATADA", DbType="NVarChar(255)")]
		public string INFORMACAO_UNIDADE_ARREMATADA
		{
			get
			{
				return this._INFORMACAO_UNIDADE_ARREMATADA;
			}
			set
			{
				if ((this._INFORMACAO_UNIDADE_ARREMATADA != value))
				{
					this._INFORMACAO_UNIDADE_ARREMATADA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AREA_DE_RISCO", DbType="NVarChar(255)")]
		public string AREA_DE_RISCO
		{
			get
			{
				return this._AREA_DE_RISCO;
			}
			set
			{
				if ((this._AREA_DE_RISCO != value))
				{
					this._AREA_DE_RISCO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTERDITADOS___DEMOLIDOS", DbType="NVarChar(255)")]
		public string INTERDITADOS___DEMOLIDOS
		{
			get
			{
				return this._INTERDITADOS___DEMOLIDOS;
			}
			set
			{
				if ((this._INTERDITADOS___DEMOLIDOS != value))
				{
					this._INTERDITADOS___DEMOLIDOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITUL_EMGEA", DbType="NVarChar(255)")]
		public string TITUL_EMGEA
		{
			get
			{
				return this._TITUL_EMGEA;
			}
			set
			{
				if ((this._TITUL_EMGEA != value))
				{
					this._TITUL_EMGEA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITUL_CEF1", DbType="NVarChar(255)")]
		public string TITUL_CEF1
		{
			get
			{
				return this._TITUL_CEF1;
			}
			set
			{
				if ((this._TITUL_CEF1 != value))
				{
					this._TITUL_CEF1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOME_DO_CONDOMINIO", DbType="NVarChar(255)")]
		public string NOME_DO_CONDOMINIO
		{
			get
			{
				return this._NOME_DO_CONDOMINIO;
			}
			set
			{
				if ((this._NOME_DO_CONDOMINIO != value))
				{
					this._NOME_DO_CONDOMINIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INFORMACAO_TAX_COND_EM_DIA", DbType="NVarChar(255)")]
		public string INFORMACAO_TAX_COND_EM_DIA
		{
			get
			{
				return this._INFORMACAO_TAX_COND_EM_DIA;
			}
			set
			{
				if ((this._INFORMACAO_TAX_COND_EM_DIA != value))
				{
					this._INFORMACAO_TAX_COND_EM_DIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_TAX_CONDOMINIAL_ESTIMATIVA", DbType="Money")]
		public System.Nullable<decimal> VALOR_TAX_CONDOMINIAL_ESTIMATIVA
		{
			get
			{
				return this._VALOR_TAX_CONDOMINIAL_ESTIMATIVA;
			}
			set
			{
				if ((this._VALOR_TAX_CONDOMINIAL_ESTIMATIVA != value))
				{
					this._VALOR_TAX_CONDOMINIAL_ESTIMATIVA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXTRATO_DA_DIVIDA_CONDOMINIAL", DbType="NVarChar(255)")]
		public string EXTRATO_DA_DIVIDA_CONDOMINIAL
		{
			get
			{
				return this._EXTRATO_DA_DIVIDA_CONDOMINIAL;
			}
			set
			{
				if ((this._EXTRATO_DA_DIVIDA_CONDOMINIAL != value))
				{
					this._EXTRATO_DA_DIVIDA_CONDOMINIAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_TOTAL_DA_DIVIDA_CONDOMINIAL", DbType="Money")]
		public System.Nullable<decimal> VALOR_TOTAL_DA_DIVIDA_CONDOMINIAL
		{
			get
			{
				return this._VALOR_TOTAL_DA_DIVIDA_CONDOMINIAL;
			}
			set
			{
				if ((this._VALOR_TOTAL_DA_DIVIDA_CONDOMINIAL != value))
				{
					this._VALOR_TOTAL_DA_DIVIDA_CONDOMINIAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_DA_ATUALIZACAO", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATA_DA_ATUALIZACAO
		{
			get
			{
				return this._DATA_DA_ATUALIZACAO;
			}
			set
			{
				if ((this._DATA_DA_ATUALIZACAO != value))
				{
					this._DATA_DA_ATUALIZACAO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MESES", DbType="DateTime")]
		public System.Nullable<System.DateTime> MESES
		{
			get
			{
				return this._MESES;
			}
			set
			{
				if ((this._MESES != value))
				{
					this._MESES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_ESTIMADO_DE_REAJUSTE", DbType="DateTime")]
		public System.Nullable<System.DateTime> VALOR_ESTIMADO_DE_REAJUSTE
		{
			get
			{
				return this._VALOR_ESTIMADO_DE_REAJUSTE;
			}
			set
			{
				if ((this._VALOR_ESTIMADO_DE_REAJUSTE != value))
				{
					this._VALOR_ESTIMADO_DE_REAJUSTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INCLUSAO_DE_10TX_S__AJUIZAMENTO", DbType="Money")]
		public System.Nullable<decimal> INCLUSAO_DE_10TX_S__AJUIZAMENTO
		{
			get
			{
				return this._INCLUSAO_DE_10TX_S__AJUIZAMENTO;
			}
			set
			{
				if ((this._INCLUSAO_DE_10TX_S__AJUIZAMENTO != value))
				{
					this._INCLUSAO_DE_10TX_S__AJUIZAMENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_ESTIMADO_ATUALIZADO", DbType="Money")]
		public System.Nullable<decimal> VALOR_ESTIMADO_ATUALIZADO
		{
			get
			{
				return this._VALOR_ESTIMADO_ATUALIZADO;
			}
			set
			{
				if ((this._VALOR_ESTIMADO_ATUALIZADO != value))
				{
					this._VALOR_ESTIMADO_ATUALIZADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PGTO_DIVIDA_CONDOMINIAL", DbType="NVarChar(255)")]
		public string PGTO_DIVIDA_CONDOMINIAL
		{
			get
			{
				return this._PGTO_DIVIDA_CONDOMINIAL;
			}
			set
			{
				if ((this._PGTO_DIVIDA_CONDOMINIAL != value))
				{
					this._PGTO_DIVIDA_CONDOMINIAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_PGTO_DIVIDA", DbType="Money")]
		public System.Nullable<decimal> VALOR_PGTO_DIVIDA
		{
			get
			{
				return this._VALOR_PGTO_DIVIDA;
			}
			set
			{
				if ((this._VALOR_PGTO_DIVIDA != value))
				{
					this._VALOR_PGTO_DIVIDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCONTO_NEGOCIACAO_DIVIDA", DbType="Money")]
		public System.Nullable<decimal> DESCONTO_NEGOCIACAO_DIVIDA
		{
			get
			{
				return this._DESCONTO_NEGOCIACAO_DIVIDA;
			}
			set
			{
				if ((this._DESCONTO_NEGOCIACAO_DIVIDA != value))
				{
					this._DESCONTO_NEGOCIACAO_DIVIDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AJUIZADAS", DbType="NVarChar(255)")]
		public string AJUIZADAS
		{
			get
			{
				return this._AJUIZADAS;
			}
			set
			{
				if ((this._AJUIZADAS != value))
				{
					this._AJUIZADAS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIA_VCTO_PADRAO", DbType="Float")]
		public System.Nullable<double> DIA_VCTO_PADRAO
		{
			get
			{
				return this._DIA_VCTO_PADRAO;
			}
			set
			{
				if ((this._DIA_VCTO_PADRAO != value))
				{
					this._DIA_VCTO_PADRAO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PGTO_OCUPANTE", DbType="NVarChar(255)")]
		public string PGTO_OCUPANTE
		{
			get
			{
				return this._PGTO_OCUPANTE;
			}
			set
			{
				if ((this._PGTO_OCUPANTE != value))
				{
					this._PGTO_OCUPANTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PGTO_OUT_2020_", DbType="NVarChar(255)")]
		public string PGTO_OUT_2020_
		{
			get
			{
				return this._PGTO_OUT_2020_;
			}
			set
			{
				if ((this._PGTO_OUT_2020_ != value))
				{
					this._PGTO_OUT_2020_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_PGTO_OUT_2020", DbType="Money")]
		public System.Nullable<decimal> VALOR_PGTO_OUT_2020
		{
			get
			{
				return this._VALOR_PGTO_OUT_2020;
			}
			set
			{
				if ((this._VALOR_PGTO_OUT_2020 != value))
				{
					this._VALOR_PGTO_OUT_2020 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PGTO_NOV_2020_", DbType="NVarChar(255)")]
		public string PGTO_NOV_2020_
		{
			get
			{
				return this._PGTO_NOV_2020_;
			}
			set
			{
				if ((this._PGTO_NOV_2020_ != value))
				{
					this._PGTO_NOV_2020_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_PGTO_NOV_2020", DbType="Money")]
		public System.Nullable<decimal> VALOR_PGTO_NOV_2020
		{
			get
			{
				return this._VALOR_PGTO_NOV_2020;
			}
			set
			{
				if ((this._VALOR_PGTO_NOV_2020 != value))
				{
					this._VALOR_PGTO_NOV_2020 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PGTO_DEZ_2020_", DbType="NVarChar(255)")]
		public string PGTO_DEZ_2020_
		{
			get
			{
				return this._PGTO_DEZ_2020_;
			}
			set
			{
				if ((this._PGTO_DEZ_2020_ != value))
				{
					this._PGTO_DEZ_2020_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_PGTO_DEZ_2020", DbType="Money")]
		public System.Nullable<decimal> VALOR_PGTO_DEZ_2020
		{
			get
			{
				return this._VALOR_PGTO_DEZ_2020;
			}
			set
			{
				if ((this._VALOR_PGTO_DEZ_2020 != value))
				{
					this._VALOR_PGTO_DEZ_2020 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PGTO_JAN_2021", DbType="NVarChar(255)")]
		public string PGTO_JAN_2021
		{
			get
			{
				return this._PGTO_JAN_2021;
			}
			set
			{
				if ((this._PGTO_JAN_2021 != value))
				{
					this._PGTO_JAN_2021 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_PGTO_JAN_2021", DbType="Money")]
		public System.Nullable<decimal> VALOR_PGTO_JAN_2021
		{
			get
			{
				return this._VALOR_PGTO_JAN_2021;
			}
			set
			{
				if ((this._VALOR_PGTO_JAN_2021 != value))
				{
					this._VALOR_PGTO_JAN_2021 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PGTO_FEV_2021", DbType="NVarChar(255)")]
		public string PGTO_FEV_2021
		{
			get
			{
				return this._PGTO_FEV_2021;
			}
			set
			{
				if ((this._PGTO_FEV_2021 != value))
				{
					this._PGTO_FEV_2021 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_PGTO_FEV_2021", DbType="Money")]
		public System.Nullable<decimal> VALOR_PGTO_FEV_2021
		{
			get
			{
				return this._VALOR_PGTO_FEV_2021;
			}
			set
			{
				if ((this._VALOR_PGTO_FEV_2021 != value))
				{
					this._VALOR_PGTO_FEV_2021 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PGTO_MAR_2021", DbType="NVarChar(255)")]
		public string PGTO_MAR_2021
		{
			get
			{
				return this._PGTO_MAR_2021;
			}
			set
			{
				if ((this._PGTO_MAR_2021 != value))
				{
					this._PGTO_MAR_2021 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_PGTO_MAR_2021", DbType="Money")]
		public System.Nullable<decimal> VALOR_PGTO_MAR_2021
		{
			get
			{
				return this._VALOR_PGTO_MAR_2021;
			}
			set
			{
				if ((this._VALOR_PGTO_MAR_2021 != value))
				{
					this._VALOR_PGTO_MAR_2021 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PGTO_ABR_2021", DbType="NVarChar(255)")]
		public string PGTO_ABR_2021
		{
			get
			{
				return this._PGTO_ABR_2021;
			}
			set
			{
				if ((this._PGTO_ABR_2021 != value))
				{
					this._PGTO_ABR_2021 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_PGTO_ABR_2021", DbType="Money")]
		public System.Nullable<decimal> VALOR_PGTO_ABR_2021
		{
			get
			{
				return this._VALOR_PGTO_ABR_2021;
			}
			set
			{
				if ((this._VALOR_PGTO_ABR_2021 != value))
				{
					this._VALOR_PGTO_ABR_2021 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNPJ_CONDOMINIO", DbType="NVarChar(255)")]
		public string CNPJ_CONDOMINIO
		{
			get
			{
				return this._CNPJ_CONDOMINIO;
			}
			set
			{
				if ((this._CNPJ_CONDOMINIO != value))
				{
					this._CNPJ_CONDOMINIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_CNPJ_CONDOMINIO", DbType="NVarChar(255)")]
		public string N_CNPJ_CONDOMINIO
		{
			get
			{
				return this._N_CNPJ_CONDOMINIO;
			}
			set
			{
				if ((this._N_CNPJ_CONDOMINIO != value))
				{
					this._N_CNPJ_CONDOMINIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONDOMINIO_INFORMAL_RATEIO", DbType="Float")]
		public System.Nullable<double> CONDOMINIO_INFORMAL_RATEIO
		{
			get
			{
				return this._CONDOMINIO_INFORMAL_RATEIO;
			}
			set
			{
				if ((this._CONDOMINIO_INFORMAL_RATEIO != value))
				{
					this._CONDOMINIO_INFORMAL_RATEIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTATO_DIRETO_CONDOMINIO", DbType="NVarChar(255)")]
		public string CONTATO_DIRETO_CONDOMINIO
		{
			get
			{
				return this._CONTATO_DIRETO_CONDOMINIO;
			}
			set
			{
				if ((this._CONTATO_DIRETO_CONDOMINIO != value))
				{
					this._CONTATO_DIRETO_CONDOMINIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOME_SINDICO", DbType="NVarChar(255)")]
		public string NOME_SINDICO
		{
			get
			{
				return this._NOME_SINDICO;
			}
			set
			{
				if ((this._NOME_SINDICO != value))
				{
					this._NOME_SINDICO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONE_SINDICO", DbType="NVarChar(255)")]
		public string TELEFONE_SINDICO
		{
			get
			{
				return this._TELEFONE_SINDICO;
			}
			set
			{
				if ((this._TELEFONE_SINDICO != value))
				{
					this._TELEFONE_SINDICO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL_SINDICO_OU_CONDOMINIO", DbType="NVarChar(255)")]
		public string EMAIL_SINDICO_OU_CONDOMINIO
		{
			get
			{
				return this._EMAIL_SINDICO_OU_CONDOMINIO;
			}
			set
			{
				if ((this._EMAIL_SINDICO_OU_CONDOMINIO != value))
				{
					this._EMAIL_SINDICO_OU_CONDOMINIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTATO_ADMINISTRADORA", DbType="NVarChar(255)")]
		public string CONTATO_ADMINISTRADORA
		{
			get
			{
				return this._CONTATO_ADMINISTRADORA;
			}
			set
			{
				if ((this._CONTATO_ADMINISTRADORA != value))
				{
					this._CONTATO_ADMINISTRADORA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOME_ADMINISTRADORA", DbType="NVarChar(255)")]
		public string NOME_ADMINISTRADORA
		{
			get
			{
				return this._NOME_ADMINISTRADORA;
			}
			set
			{
				if ((this._NOME_ADMINISTRADORA != value))
				{
					this._NOME_ADMINISTRADORA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNPJ_ADMINISTRADORA", DbType="NVarChar(255)")]
		public string CNPJ_ADMINISTRADORA
		{
			get
			{
				return this._CNPJ_ADMINISTRADORA;
			}
			set
			{
				if ((this._CNPJ_ADMINISTRADORA != value))
				{
					this._CNPJ_ADMINISTRADORA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAIRRO", DbType="NVarChar(255)")]
		public string BAIRRO
		{
			get
			{
				return this._BAIRRO;
			}
			set
			{
				if ((this._BAIRRO != value))
				{
					this._BAIRRO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEP", DbType="NVarChar(255)")]
		public string CEP
		{
			get
			{
				return this._CEP;
			}
			set
			{
				if ((this._CEP != value))
				{
					this._CEP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_DE_AVALIACAO", DbType="Money")]
		public System.Nullable<decimal> VALOR_DE_AVALIACAO
		{
			get
			{
				return this._VALOR_DE_AVALIACAO;
			}
			set
			{
				if ((this._VALOR_DE_AVALIACAO != value))
				{
					this._VALOR_DE_AVALIACAO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OCUPACAO", DbType="NVarChar(255)")]
		public string OCUPACAO
		{
			get
			{
				return this._OCUPACAO;
			}
			set
			{
				if ((this._OCUPACAO != value))
				{
					this._OCUPACAO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHAVES", DbType="NVarChar(255)")]
		public string CHAVES
		{
			get
			{
				return this._CHAVES;
			}
			set
			{
				if ((this._CHAVES != value))
				{
					this._CHAVES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[OBS:]", Storage="_OBS_", DbType="NVarChar(255)")]
		public string OBS_
		{
			get
			{
				return this._OBS_;
			}
			set
			{
				if ((this._OBS_ != value))
				{
					this._OBS_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOTOS", DbType="NVarChar(255)")]
		public string FOTOS
		{
			get
			{
				return this._FOTOS;
			}
			set
			{
				if ((this._FOTOS != value))
				{
					this._FOTOS = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
